sudo: false

language: node_js

node_js:
  - "10"

dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href="https://solareenlo.github.io/mean-stack01/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
